[package]
name = "sob"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
hex = "0.4.3"
lazy_static = "1.4.0"
libsecp256k1 = "0.7.1"
ripemd = "0.1.3"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
sha1 = "0.10.6"
sha2 = "0.10.8"
